### ISSUE TITLE
share screen for specific window or application

### ISSUE THREAD

**Issue by jordanhurst** [bitfocus/companion-module-cisco-roomos#15]
This is a feature I've been trying to find for some time.  and it may just not be possible with the way Webex sets up the share screen dialog.  is it possible to share a specific application/window/file/etc with a single keystroke?  I'd love to be able to make one button on my deck that starts sharing and chooses the correct source, instead of just bringing the screen sharing dialog.

**Comment by SveinTerje** [comment]
This issue seems to be related to Webex App, not the hardware devices, so it may not fit in this category, as the module is only connecting to the hardware devices with xAPI, effectively running RoomOS.

I will agree the naming has been a bit confusing, being "Webex Devices", so Cisco has now renamed them to "Cisco Devices", as they do support multiple meeting platforms.
